### PR TITLE
Align with new versions of Rubocop and Devtools

### PR DESCRIPTION
**Pull request by alejandrobabio**
These changes were done in order to put build status in green again.

Any comment or code review is welcome.

### CODE REVIEW

**Comment by mbj** [comment]
@alejandrobabio I'm fine with this changes, but have to get CI green again. The Circle integration was broken and at the time I wanted to re-activate it Circle had problems. I'll retry when I've time to do OSS which may is a way in the future.

**Comment by alejandrobabio** [comment]
Hi, @mbj I did run my fork on Circle, and it passes. You can see it [here](https://circleci.com/gh/alejandrobabio/anima/1).

I realise that is needed another change here. The readme build icon is the Travis' one and should be changed to the Circle's. I did change it but seems to not work. I'll do some research tomorrow.

**Comment by mbj** [comment]
> Hi, @mbj I did run my fork on Circle, and it passes. You can see it here.
> 
> I realise that is needed another change here. The readme build icon is the Travis' one and should be changed to the Circle's. I did change it but seems to not work. I'll do some research tomorrow.

My point is that the GH hooks for this Project connecting to Circle are not setup correctly right now. I still need time to do that as the automated setup was broken the last time I tried.

**Comment by alejandrobabio** [comment]
OK. Just let me know if you need something from me.

**Comment by mbj** [comment]
> OK. Just let me know if you need something from me.

Wish me luck to carve out OSS time ;)

**Comment by mbj** [comment]
@alejandrobabio I'll close this now as this was done as part of #31

**Pull request closed without merging**
